name: Build and push Docker image to Docker Hub
on:
  push:
    branches:
      - dev
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and tag Docker image
        run: |
          docker build -t rclsilver/monitoring-daemon:latest -f daemon/Dockerfile .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image to Docker Hub
        run: |
          docker push rclsilver/monitoring-daemon:latest
